<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EncadrantAcademiqueSeeder extends Seeder
{
    public function run(): void
    {
        $encadrants = [
            [
                'nom' => 'STITOU',
                'prenom' => 'Mostafa',
                'grade' => 'Professeur',
                'specialite' => 'Informatique',
                'email' => 'm.stitou@ensa-tetouan.ac.ma',
                'telephone' => '+212612345678',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'BENKADDOUR',
                'prenom' => 'Abdelhamid',
                'grade' => 'Professeur',
                'specialite' => 'Génie Logiciel',
                'email' => 'a.benkaddour@ensa-tetouan.ac.ma',
                'telephone' => '+212612345679',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'ABTOY',
                'prenom' => 'Anouar',
                'grade' => 'Professeur',
                'specialite' => 'Réseaux',
                'email' => 'a.abtoy@ensa-tetouan.ac.ma',
                'telephone' => '+212612345680',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'ACHEGAF',
                'prenom' => 'Zineb',
                'grade' => 'Professeur',
                'specialite' => 'Intelligence Artificielle',
                'email' => 'z.achegaf@ensa-tetouan.ac.ma',
                'telephone' => '+212612345681',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'AGHZOUT',
                'prenom' => 'Otman',
                'grade' => 'Professeur',
                'specialite' => 'Systèmes Embarqués',
                'email' => 'o.aghzout@ensa-tetouan.ac.ma',
                'telephone' => '+212612345682',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'AL ACHHAB',
                'prenom' => 'Mohammed',
                'grade' => 'Professeur',
                'specialite' => 'Traitement du Signal',
                'email' => 'm.alachhab@ensa-tetouan.ac.ma',
                'telephone' => '+212612345683',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'AMELLAL',
                'prenom' => 'Issam',
                'grade' => 'Professeur',
                'specialite' => 'Sécurité Informatique',
                'email' => 'i.amellal@ensa-tetouan.ac.ma',
                'telephone' => '+212612345684',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'AOULAD BENZEROUALA',
                'prenom' => 'Rachad',
                'grade' => 'Professeur',
                'specialite' => 'Bases de Données',
                'email' => 'r.auladb@ensa-tetouan.ac.ma',
                'telephone' => '+212612345685',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'ARIOUA',
                'prenom' => 'Mounir',
                'grade' => 'Professeur',
                'specialite' => 'Cloud Computing',
                'email' => 'm.arioua@ensa-tetouan.ac.ma',
                'telephone' => '+212612345686',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'ATTAJKANI',
                'prenom' => 'Sabri',
                'grade' => 'Professeur',
                'specialite' => 'Machine Learning',
                'email' => 's.attajkani@ensa-tetouan.ac.ma',
                'telephone' => '+212612345687',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'AZEROUAL',
                'prenom' => 'Boubker',
                'grade' => 'Professeur',
                'specialite' => 'Développement Web',
                'email' => 'b.azeroual@ensa-tetouan.ac.ma',
                'telephone' => '+212612345688',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'BANNOUR',
                'prenom' => 'Abdelilah',
                'grade' => 'Professeur',
                'specialite' => 'IoT',
                'email' => 'a.bannour@ensa-tetouan.ac.ma',
                'telephone' => '+212612345689',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'EL-BAKARI',
                'prenom' => 'Abdelali',
                'grade' => 'Professeur',
                'specialite' => 'Télécommunications',
                'email' => 'a.elbakari@ensa-tetouan.ac.ma',
                'telephone' => '+212612345690',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'BENBOUBKER',
                'prenom' => 'Mohamed Badr',
                'grade' => 'Professeur',
                'specialite' => 'Data Science',
                'email' => 'mb.benboubker@ensa-tetouan.ac.ma',
                'telephone' => '+212612345691',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'BENTAJER',
                'prenom' => 'Ahmed',
                'grade' => 'Professeur',
                'specialite' => 'Algorithmique',
                'email' => 'a.bentajer@ensa-tetouan.ac.ma',
                'telephone' => '+212612345692',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'BESRI',
                'prenom' => 'Zineb',
                'grade' => 'Professeur',
                'specialite' => 'Vision Artificielle',
                'email' => 'z.besri@ensa-tetouan.ac.ma',
                'telephone' => '+212612345693',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'BOLAJRAF',
                'prenom' => 'Mohamed',
                'grade' => 'Professeur',
                'specialite' => 'Robotique',
                'email' => 'm.bolajraf@ensa-tetouan.ac.ma',
                'telephone' => '+212612345694',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'BOUNAB',
                'prenom' => 'Loubna',
                'grade' => 'Professeur',
                'specialite' => 'Big Data',
                'email' => 'l.bounab@ensa-tetouan.ac.ma',
                'telephone' => '+212612345695',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'CHAKKOR',
                'prenom' => 'Otman',
                'grade' => 'Professeur',
                'specialite' => 'Cybersécurité',
                'email' => 'o.chakkor@ensa-tetouan.ac.ma',
                'telephone' => '+212612345696',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'CHEKOURI',
                'prenom' => 'Mohamed Yassin',
                'grade' => 'Professeur',
                'specialite' => 'DevOps',
                'email' => 'my.chekouri@ensa-tetouan.ac.ma',
                'telephone' => '+212612345697',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'CHERKAOUI',
                'prenom' => 'Mohamed',
                'grade' => 'Professeur',
                'specialite' => 'Réseaux 5G',
                'email' => 'm.cherkaoi@ensa-tetouan.ac.ma',
                'telephone' => '+212612345698',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'DKHISSI',
                'prenom' => 'Btissam',
                'grade' => 'Professeur',
                'specialite' => 'Blockchain',
                'email' => 'b.dkhissi@ensa-tetouan.ac.ma',
                'telephone' => '+212612345699',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'ECH-CHERRAT',
                'prenom' => 'Mohamed Reda',
                'grade' => 'Professeur',
                'specialite' => 'Automatique',
                'email' => 'mr.echcherrat@ensa-tetouan.ac.ma',
                'telephone' => '+212612345700',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'EL ADIB',
                'prenom' => 'Samir',
                'grade' => 'Professeur',
                'specialite' => 'Multimédia',
                'email' => 's.eladib@ensa-tetouan.ac.ma',
                'telephone' => '+212612345701',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'EL BIARI',
                'prenom' => 'Aouatef',
                'grade' => 'Professeur',
                'specialite' => 'Data Mining',
                'email' => 'a.elbiari@ensa-tetouan.ac.ma',
                'telephone' => '+212612345702',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'EL BOUHDIDI',
                'prenom' => 'Jaber',
                'grade' => 'Professeur',
                'specialite' => 'Énergie',
                'email' => 'j.elbouhdidi@ensa-tetouan.ac.ma',
                'telephone' => '+212612345703',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'EL FALLAHI',
                'prenom' => 'Abdellah',
                'grade' => 'Professeur',
                'specialite' => 'Optimisation',
                'email' => 'a.elfallahi@ensa-tetouan.ac.ma',
                'telephone' => '+212612345704',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'EL HAJJAMY',
                'prenom' => 'Oussama',
                'grade' => 'Professeur',
                'specialite' => 'IA et Deep Learning',
                'email' => 'o.elhajjamy@ensa-tetouan.ac.ma',
                'telephone' => '+212612345705',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'EL KADDOURI',
                'prenom' => 'Abdelmonaim',
                'grade' => 'Professeur',
                'specialite' => 'Statistiques',
                'email' => 'a.elkaddouri@ensa-tetouan.ac.ma',
                'telephone' => '+212612345706',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'EL KHAMLICHI',
                'prenom' => 'Yasser',
                'grade' => 'Professeur',
                'specialite' => 'Finance Quantitative',
                'email' => 'y.elkhamlichi@ensa-tetouan.ac.ma',
                'telephone' => '+212612345707',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'EL KHANNOUSSI',
                'prenom' => 'Fadoua',
                'grade' => 'Professeur',
                'specialite' => 'Traitement d\'Images',
                'email' => 'f.elkhannoussi@ensa-tetouan.ac.ma',
                'telephone' => '+212612345708',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'EL YOUNOUSSI',
                'prenom' => 'Yacine',
                'grade' => 'Professeur',
                'specialite' => 'Simulation',
                'email' => 'y.elyounoussi@ensa-tetouan.ac.ma',
                'telephone' => '+212612345709',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'HADDI',
                'prenom' => 'Ali',
                'grade' => 'Professeur',
                'specialite' => 'Calcul Scientifique',
                'email' => 'a.haddi@ensa-tetouan.ac.ma',
                'telephone' => '+212612345710',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'HAJJAJI',
                'prenom' => 'Anas',
                'grade' => 'Professeur',
                'specialite' => 'Automatique Avancée',
                'email' => 'a.hajjaji@ensa-tetouan.ac.ma',
                'telephone' => '+212612345711',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'JOURANI',
                'prenom' => 'Reda',
                'grade' => 'Professeur',
                'specialite' => 'Systèmes Distribués',
                'email' => 'r.jourani@ensa-tetouan.ac.ma',
                'telephone' => '+212612345712',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'KHAMLICHI',
                'prenom' => 'Abdellatif',
                'grade' => 'Professeur',
                'specialite' => 'Mathématiques Appliquées',
                'email' => 'a.khamlichi@ensa-tetouan.ac.ma',
                'telephone' => '+212612345713',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'KHOULJI',
                'prenom' => 'Samira',
                'grade' => 'Professeur',
                'specialite' => 'Bioinformatique',
                'email' => 's.khoulji@ensa-tetouan.ac.ma',
                'telephone' => '+212612345714',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'LAJJAM',
                'prenom' => 'Azza',
                'grade' => 'Professeur',
                'specialite' => 'Qualité Logicielle',
                'email' => 'a.lajjam@ensa-tetouan.ac.ma',
                'telephone' => '+212612345715',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'LOULY',
                'prenom' => 'Adil',
                'grade' => 'Professeur',
                'specialite' => 'Architecture Logicielle',
                'email' => 'a.louly@ensa-tetouan.ac.ma',
                'telephone' => '+212612345716',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'MAHBOUB',
                'prenom' => 'Oussama',
                'grade' => 'Professeur',
                'specialite' => 'Ingénierie des Données',
                'email' => 'o.mahboub@ensa-tetouan.ac.ma',
                'telephone' => '+212612345717',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'MEDOURI',
                'prenom' => 'Abdellatif',
                'grade' => 'Professeur',
                'specialite' => 'Probabilités',
                'email' => 'a.medouri@ensa-tetouan.ac.ma',
                'telephone' => '+212612345718',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'MESMOUDI',
                'prenom' => 'Yasser',
                'grade' => 'Professeur',
                'specialite' => 'Analyse Numérique',
                'email' => 'y.mesmoudi@ensa-tetouan.ac.ma',
                'telephone' => '+212612345719',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'NASRI',
                'prenom' => 'Khalid',
                'grade' => 'Professeur',
                'specialite' => 'Recherche Opérationnelle',
                'email' => 'k.nasri@ensa-tetouan.ac.ma',
                'telephone' => '+212612345720',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'OUAKKASSE',
                'prenom' => 'Noureddine',
                'grade' => 'Professeur',
                'specialite' => 'Optimisation Combinatoire',
                'email' => 'n.ouakkasse@ensa-tetouan.ac.ma',
                'telephone' => '+212612345721',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'RAISSOUNI',
                'prenom' => 'Naoufal',
                'grade' => 'Professeur',
                'specialite' => 'Théorie de l\'Information',
                'email' => 'n.raissouni@ensa-tetouan.ac.ma',
                'telephone' => '+212612345722',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'SANBI',
                'prenom' => 'Mustapha',
                'grade' => 'Professeur',
                'specialite' => 'Théorie des Graphes',
                'email' => 'm.sanbi@ensa-tetouan.ac.ma',
                'telephone' => '+212612345723',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'SARIR',
                'prenom' => 'Hicham',
                'grade' => 'Professeur',
                'specialite' => 'Codage et Théorie de l\'Information',
                'email' => 'h.sarir@ensa-tetouan.ac.ma',
                'telephone' => '+212612345724',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'SEGHIOUER',
                'prenom' => 'Hamid',
                'grade' => 'Professeur',
                'specialite' => 'Traitement du Signal Avancé',
                'email' => 'h.seghiouer@ensa-tetouan.ac.ma',
                'telephone' => '+212612345725',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'TAHIRI',
                'prenom' => 'Abderrahim',
                'grade' => 'Professeur',
                'specialite' => 'Automatique et Contrôle',
                'email' => 'a.tahiri@ensa-tetouan.ac.ma',
                'telephone' => '+212612345726',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'ZAKRITI',
                'prenom' => 'Alia',
                'grade' => 'Professeur',
                'specialite' => 'Analyse de Données',
                'email' => 'a.zakriti@ensa-tetouan.ac.ma',
                'telephone' => '+212612345727',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'ZLAIJI',
                'prenom' => 'Loubna',
                'grade' => 'Professeur',
                'specialite' => 'Intelligence Artificielle Appliquée',
                'email' => 'l.zlaiji@ensa-tetouan.ac.ma',
                'telephone' => '+212612345728',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('encadrant_academique')->insert($encadrants);
    }
}
